### ISSUE TITLE
Github Actions CI w/ action-rs/toolchain is not setting rustversion properly

### ISSUE THREAD

**Issue by chipsenkbeil** [dtolnay/rustversion#25]
For my project [entity-rs](https://github.com/chipsenkbeil/entity-rs), I have a single [CI.yml workflow](https://github.com/chipsenkbeil/entity-rs/blob/main/.github/workflows/ci.yml) that has a setup like this:

![Screen Shot 2021-01-06 at 10 35 05 AM](https://user-images.githubusercontent.com/2481802/103794860-dd710a00-500a-11eb-8230-5ab6e0443792.png)

In my macro crate within the project, I'm using [trybuild in my tests](https://github.com/chipsenkbeil/entity-rs/blob/main/entity_macros/tests/lib.rs) and - like I'd seen in discussions on Github - have it set to only run when the Rust version is nightly:

![Screen Shot 2021-01-06 at 10 36 35 AM](https://user-images.githubusercontent.com/2481802/103795019-1315f300-500b-11eb-95e6-27e7542c524c.png)

This works great if I run `cargo +nightly test` from within `entity-rs/entity_macros` or if I run `cargo +nightly test --workspace` from the root of `entity-rs`, but for whatever reason my Github action continues to mark the UI tests as ignore for nightly versions of Rust:

![Screen Shot 2021-01-06 at 10 38 19 AM](https://user-images.githubusercontent.com/2481802/103795215-51131700-500b-11eb-8343-4c7a090946d1.png)

Is there something else I need to configure on the CI-side? Or maybe I misunderstood something? I've been trying to read through different sources where people are using rustversion in combination with trybuild and haven't noticed anything yet.

**Comment by taiki-e** [comment]
> ```yaml
>      - uses: actions-rs/toolchain@v1
>        with:
>          toolchain: ${{ matrix.rust }}
> ```


`actions-rs/toolchain` does not override the default toolchain.
You need to use `override: true` or `default: true`. See also https://github.com/actions-rs/toolchain/blob/master/README.md#inputs

**Comment by chipsenkbeil** [comment]
Ah, didn't realize that. I'll close this out. Thanks!
