### ISSUE TITLE
Drop Edition 2018?

### ISSUE THREAD

**Issue by JeremyRubin** [dtolnay/rustversion#27]
Is it possible to make this crate have an edition of 2015 implicitly so that it can be used on pre-1.31 code?

**Comment by dtolnay** [comment]
It's possible. What compiler version do you care about support for?

**Comment by JeremyRubin** [comment]
rust-bitcoin targest MSRV 1.29; not a huge deal because issues with dev-dependencies means that this won't exactly fix our problem either, but perhaps worth addressing in general for rustversion as I'd imagine being able to use version switching macros on the widest set of versions is a good goal.

**Comment by dtolnay** [comment]
1.29 does not support attribute macros so that would require a different approach than rustversion.
