### ISSUE TITLE
README.md (and thus rust docs) are stale

### ISSUE THREAD

**Issue by rbtcollins** [dtolnay/rustversion#33]
Looks like #[rustversion::any....] is the right syntax now, but the published docs still claim #[rustc::nightly]... etc

**Comment by rbtcollins** [comment]
Argh no, its different.

rustc-select still exists and has googlejuice.

Perhaps do a 0.1.3 of rustc-select that will fail to compile and point people at rustversion?

**Comment by dtolnay** [comment]
I yanked all the select-rustc releases because rustc has refused to compile them for a long time (#6).
