### ISSUE TITLE
Differentiating stable with no fixed version

### ISSUE THREAD

**Issue by peter-kehl** [dtolnay/rustversion#39]
Hi David,

Am I right that the versions come from `rustc`, not from `cargo` nor `rustup`'s default/overridden toolchain (and neither `cargo`, nor `rustup` need to be installed at all)?

Otherwise - in addition to
- `#[rustversion::stable]` matching **any** stable, and
- `#[rustversion::stable(1.34)]` matching only that fixed stable, how about
- `#[rustversion::stable(*)]` (or `#[rustversion::stable(float)]` or other) to match when we are on `rustup default stable` (and the version is not fixed, but will increase with `rustup update`), please?

(If the above is not possible, then for anyone's reference: `cargo_toolchain` crate supports that - but then I use both `rustversion` and `cargo_toolchain`.)

Either way, thank you for all your crates. Take care.

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate. But someone could make a more fully featured version selection crate that could build in this interaction with rustup.
