### ISSUE TITLE
Possible to support #[rustc::minimum(1.27)] or the like?

### ISSUE THREAD

**Issue by mathstuf** [dtolnay/rustversion#4]
Using attributes which are always-true or always-false under this would then warn/error about being a tautology. This would help make sure that as the minimum version is bumped, old code/checks go away.

It would also act as documentation for the minimum version allowed. (AFAIK, still waiting on that field in `Cargo.toml`).

**Comment by dtolnay** [comment]
Seems reasonable. I would accept a PR implementing this.

**Comment by mathstuf** [comment]
Looks like there's a [merged RFC for this now](https://github.com/rust-lang/rfcs/pull/2523), so I'll close this in preference for that.
