### ISSUE TITLE
When to rerun if a source file changed

### ISSUE THREAD

**Issue by hkBst** [dtolnay/rustversion#45]
Current rerun-if directives include just the build/build.rs file itself, but not its cousin build/rustc.rs. Shouldn't the entire build directory be used instead? That way cargo will rerun if any of the files in build/ changes.

**Comment by dtolnay** [comment]
I believe this already works correctly as currently implemented. If you are able to demonstrate the build script not being recompiled and rerun after a rustc.rs change, please share it.
