### ISSUE TITLE
Analog to std::cfg! macro

### ISSUE THREAD

**Issue by CreepySkeleton** [dtolnay/rustversion#7]
Sometimes it's neat to have a macro expanding to `true` or`false` instead of attribute. I propose to implement `rusversion::cfg!(stable...)` macro.

By the way, I believe it can be implemented via
```rust
macro_rules! cfg {
    ($(tts:tt)*) => {{
        #[rustversion::$(tts)*] fn do_cfg() { true }
        #[rustversion::not($(tts)*)] fn do_cfg() { false }

        do_cfg()
    }}
}
```

**Comment by jhpratt** [comment]
@dtolnay Function-like and attribute macros can exist in the same crate with the same name, correct? If so, I think this should be relatively easy to modify the existing code to add support for this. I may be able to do it if my understanding is correct.
