### ISSUE TITLE
Disable unstable feature

### ISSUE THREAD

**Issue by CodeSandwich** [dtolnay/rustversion#8]
I'd like to use an unstable feature only when crate is compiled with nightly. Is it possible to annotate the `#![feature(unstable_feature)]` line so it's visible only for nightly compiler?

**Comment by dtolnay** [comment]
I think you would need to add a build.rs script:

```rust
#[rustversion::nightly]
fn main() {
    println!("cargo:rustc-cfg=unstable_feature");
}

#[rustversion::not(nightly)]
fn main() {}
```

and then do:

```rust
#![cfg_attr(unstable_feature, feature(unstable_feature))]
```

**Comment by WorldSEnder** [comment]
A bit nicer to read with `rustversion::cfg!` macro now (which isn't directly mentioned in the readme)

```rust
fn main() {
    if rustversion::cfg!(nightly) {
        println!("cargo:rustc-cfg=unstable_feature");
    }
}
```

**Comment by caass** [comment]
Seeing as this is still a thing, it might be nice to mention this build.rs usage in the readme?
